### ISSUE TITLE
Can't get kedro-airflow to create DAGS

### ISSUE THREAD

**Issue by evanmiller29** [quantumblacklabs/kedro-airflow#20]
## Description
I have installed airflow, kedro and kedro-airflow on a docker image but i can't translate my pipeline into DAGs.

## Context
I have been running `kedro airflow create` but I keep getting an error

## Steps to Reproduce

#1 git clone my repo https://github.com/evanmiller29/kedro-airflow-test
#2 cd into folder
#3 If on windows machine run build_run_image.ps1 otherwise run the commands in the file via bash

## Expected Result
I was hoping that the plugin would convert the pipeline elements to DAGs 

## Actual Result

**First I get a warning about the plugins**

 Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/kedro/cli/cli.py", line 574, in _get_plugin_command_groups
  command_groups.append(entry_point.load())
File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
  self.require(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
  items = working_set.resolve(reqs, env, installer, extras=self.extras)
File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
  raise VersionConflict(dist, req).with_context(dependent_req)
 pkg_resources.ContextualVersionConflict: (tzlocal 2.0.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('tzlocal<2.0.0.0,>=1.5.0.0'), {'pendulum'})
 Error: Loading project commands from airflow = kedro_airflow.plugin:commands

**Kedro test pipelines execute correctly**

 2019-08-22 09:26:41,092 - root - INFO - ** Kedro project airflow_test
 2019-08-22 09:26:41,134 - kedro.io.data_catalog - INFO - Loading data from `example_iris_data` (CSVLocalDataSet)...
 2019-08-22 09:26:41,146 - kedro.io.data_catalog - INFO - Loading data from `params:example_test_data_ratio` (MemoryDataSet)...
 2019-08-22 09:26:41,147 - kedro.pipeline.node - INFO - Running node: split_data([example_iris_data,params:example_test_data_ratio]) -> [example_test_x,example_test_y,example_train_x,example_train_y]
 2019-08-22 09:26:41,170 - kedro.io.data_catalog - INFO - Saving data to `example_train_x` (MemoryDataSet)...
 2019-08-22 09:26:41,173 - kedro.io.data_catalog - INFO - Saving data to `example_train_y` (MemoryDataSet)...
 2019-08-22 09:26:41,176 - kedro.io.data_catalog - INFO - Saving data to `example_test_x` (MemoryDataSet)...
 2019-08-22 09:26:41,178 - kedro.io.data_catalog - INFO - Saving data to `example_test_y` (MemoryDataSet)...
 2019-08-22 09:26:41,179 - kedro.runner.sequential_runner - INFO - Completed 1 out of 4 tasks
 2019-08-22 09:26:41,179 - kedro.io.data_catalog - INFO - Loading data from `example_train_x` (MemoryDataSet)...
 2019-08-22 09:26:41,180 - kedro.io.data_catalog - INFO - Loading data from `example_train_y` (MemoryDataSet)...
 2019-08-22 09:26:41,180 - kedro.io.data_catalog - INFO - Loading data from `parameters` (MemoryDataSet)...
 2019-08-22 09:26:41,180 - kedro.pipeline.node - INFO - Running node: train_model([example_train_x,example_train_y,parameters]) -> [example_model]
 2019-08-22 09:26:41,635 - kedro.io.data_catalog - INFO - Saving data to `example_model` (MemoryDataSet)...
 2019-08-22 09:26:41,636 - kedro.runner.sequential_runner - INFO - Completed 2 out of 4 tasks
 2019-08-22 09:26:41,636 - kedro.io.data_catalog - INFO - Loading data from `example_model` (MemoryDataSet)...
 2019-08-22 09:26:41,638 - kedro.io.data_catalog - INFO - Loading data from `example_test_x` (MemoryDataSet)...
 2019-08-22 09:26:41,639 - kedro.pipeline.node - INFO - Running node: predict([example_model,example_test_x]) -> [example_predictions]
 2019-08-22 09:26:41,639 - kedro.io.data_catalog - INFO - Saving data to `example_predictions` (MemoryDataSet)...
 2019-08-22 09:26:41,640 - kedro.runner.sequential_runner - INFO - Completed 3 out of 4 tasks
 2019-08-22 09:26:41,640 - kedro.io.data_catalog - INFO - Loading data from `example_predictions` (MemoryDataSet)...
 2019-08-22 09:26:41,641 - kedro.io.data_catalog - INFO - Loading data from `example_test_y` (MemoryDataSet)...
 2019-08-22 09:26:41,641 - kedro.pipeline.node - INFO - Running node: report_accuracy([example_predictions,example_test_y]) -> None
 2019-08-22 09:26:41,642 - airflow_test.nodes.example - INFO - Model accuracy on test set: 93.33%
 2019-08-22 09:26:41,642 - kedro.runner.sequential_runner - INFO - Completed 4 out of 4 tasks
 2019-08-22 09:26:41,643 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.

**Then I get an error saying that kedro doesn't have an airflow option**

 Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/kedro/cli/cli.py", line 574, in _get_plugin_command_groups
  command_groups.append(entry_point.load())
File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
  self.require(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
  items = working_set.resolve(reqs, env, installer, extras=self.extras)
File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
  raise VersionConflict(dist, req).with_context(dependent_req)
 pkg_resources.ContextualVersionConflict: (tzlocal 2.0.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('tzlocal<2.0.0.0,>=1.5.0.0'), {'pendulum'})
 Error: Loading project commands from airflow = kedro_airflow.plugin:commands
 Usage: kedro [OPTIONS] COMMAND [ARGS]...
 Try "kedro -h" for help.

 Error: No such command "airflow".

## Your Environment
Include as many relevant details about the environment you experienced the bug in:

* Kedro-Airflow plugin version used (get it by running `pip show kedro-airflow`): 0.1.0
* Airflow version (`airflow --version`): v1.10.3
* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.0
* Python version used (`python -V`): 3.6.9
* Operating system and version:

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by tolomea** [comment]
This is caused by dependency version issues. Could you please try the following:
1: make sure `kedro-airflow` is in `requirements.txt`
2: run `kedro build-reqs` this will use pip compile to intelligently resolve dependency versions
3: run `kedro install` to update your installed dependencies
4: try `kedro airflow create` again

**Comment by tolomea** [comment]
@yetudada Maybe we should catch `ContextualVersionConflict` exceptions coming out of plugins and show the user a message suggesting they try `build-reqs`

**Comment by evanmiller29** [comment]
@tolomea thanks for the quick response. kedro-airflow is already in the requirements.txt for the docker image, do you want me to put it in the project requirements.txt too?

**Comment by evanmiller29** [comment]
@tolomea - yep added it to the requirements.txt and it all works.

**Comment by tolomea** [comment]
I'm glad you got it sorted.

**Comment by evanmiller29** [comment]
@tolomea - one more question. Now I've created the DAG how do I run it on the airflow webserver? 

`dag = DAG(
    slugify("airflow_test"),
    default_args=default_args,
    schedule_interval=timedelta(days=1),
)`

Does that mean it should be called airflow_test?

**Comment by tolomea** [comment]
Yes.

If you are running Airflow on your local machine, then the command `kedro airflow deploy` will copy the dag file the dags directory under the directory given in the environment variable `AIRFLOW_HOME` (defaulting to `~/airflow`).
I recommend you run Airflow locally at first as a way to learn how the bits go together.

If you are running Airflow on a server you will need to get the dag file to the correct location and also make sure your project source and config are available to the workers.

**Comment by BernardWez** [comment]
I'm experiencing a similar issue as evanmiller29 with regard to installing the kedro-airflow plugin. After `pip install kedro-airflow` I also get the following error:
 
Error: Loading project commands from airflow = kedro_airflow.plugin:commands

As suggested above, I added kedro-airflow to the requirements.txt file and ran `kedro build-reqs`. However this gives me the following error:

No requirements.in found. Copying contents from requirements.txt...
/home/bernard/anaconda3/envs/new-heroes/bin/python -m piptools compile /mnt/c/Users/Meekmar/Github/new-heroes/src/requirements.in
Could not find a version that matches python-slugify<3.0.4,>=4.0.0 (from kedro-airflow==0.2.2->-r /mnt/c/Users/Meekmar/Github/new-heroes/src/requirements.in (line 23))
Tried: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0, 1.0.2, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.4, 1.2.5,
1.2.6, 2.0.0, 2.0.1, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 4.0.0
There are incompatible versions in the resolved dependencies:
  python-slugify<3.0.4 (from kedro-airflow==0.2.2->-r /mnt/c/Users/Meekmar/Github/new-heroes/src/requirements.in (line 23))
  python-slugify>=4.0.0 (from cookiecutter==1.7.2->kedro==0.15.9->-r /mnt/c/Users/Meekmar/Github/new-heroes/src/requirements.in (line 5))

Any suggestions how to solve this?

**Comment by 921kiyo** [comment]
@BernardWez Which version of Kedro are you using? This commit might be related https://github.com/quantumblacklabs/kedro/commit/1ccd6d41a9edf5b707ae33e167a625ff3a679bef as there was a conflict for Kedro and Kedro-Airflow dependencies since Airflow hardpinn everything in their requirements.txt. https://github.com/apache/airflow/tree/master/requirements An immediate workaround would be to set the upperpin of cookiecutter in your project as I did in the commit. Hope this helps :)

**Comment by BernardWez** [comment]
@921kiyo Working with kedro==0.15.9 currently. And yes, this was very helpful as your workaround solved the issue. Thanks!
